---
# tasks file for andras.brew-zsh
- name: Ensure brew exists
  raw: test -e  "{{ homebrew_brew_bin_path }}/brew" && echo true || echo false
  register: homebrew_installed
- name: Install iTerm2
  homebrew_cask:
    name:
      - iterm2
    state: upgraded
    update_homebrew: yes
  when: homebrew_installed == true
- name: Install zsh
  homebrew:
    name:
      - zsh
      - zsh-syntax-highlighting
    state: present
    update_homebrew: yes
  when: homebrew_installed == true
- name: Install oh-my-zsh
  shell: "sh -c \"$(curl -fsSL {{ oh_my_fish_script }})\" \"\" --unattended"
  args:
    creates: "$HOME/.oh-my-zsh/oh-my-zsh.sh"
  become: no
- name: make iterm environment file
  file:
    path: "{{ iterm_env_path }}"
    state: touch
- name: populate iterm environment file
  lineinfile:
    dest: "{{ iterm_env_path }}"
    state: present
    regexp: "^export {{ item.key }}="
    line: "export {{ item.key }}={{ item.value }}"
  with_items: "{{ iterm_environment }}"

#  zsh-autosuggestions
