---
# tasks file for andrasfindt.brew-zsh
- name: Install iTerm2
  homebrew_cask:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: present
  loop: "{{ iterm_packages }}"
  notify:
    - Clear homebrew cache
- name: Install zsh packages
  homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ brew_zsh_packages }}"
  notify:
    - Clear homebrew cache
- name: Install oh-my-zsh
  shell: "sh -c \"$(curl -fsSL {{ oh_my_fish_script }})\" \"\" --unattended"
  args:
    creates: "$HOME/.oh-my-zsh/oh-my-zsh.sh"
  become: no
- name: Set iTerm2 as default terminal
  template:
    src: 0-iterm.zsh.j2
    dest: "{{ iterm_env_path }}"
  vars:
    iterm_version: "{{ lookup('file', iterm_version_path ) }}"
- name: Install Powerline font
  copy:
    src: "SourceCodePro+Powerline+Awesome+Regular.ttf"
    dest: "~/Library/Fonts"
- name: Install iTerm2 Profile
  copy:
    src: "com.googlecode.iterm2.plist"
    dest: "~/Library/Preferences/"
- name: Install powerlevel10k oh-my-zsh theme
  git:
    repo: "{{ powerlevel10k_repo }}"
    dest: "{{ powerlevel10k_path }}"
    depth: 1
- name: Populate powerlevel10k environment file
  lineinfile:
    dest: "{{ zshrc_path }}"
    state: present
    regexp: "^(export )?{{ item.key }}="
    line: "export {{ item.key }}={{ item.value }}"
  with_items: "{{ powerlevel10k_env_vars }}"





