---
# tasks file for andrasfindt.brew-zsh
- name: Install iTerm2
  homebrew_cask:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: present
  loop: "{{ iterm_packages }}"
  notify:
    - Clear homebrew cache
- name: Install zsh packages
  homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ brew_zsh_packages }}"
  notify:
    - Clear homebrew cache
- name: Install oh-my-zsh
  shell: "sh -c \"$(curl -fsSL {{ oh_my_fish_script }})\" \"\" --unattended"
  args:
    creates: "$HOME/.oh-my-zsh/oh-my-zsh.sh"
  become: no
- name: Set iTerm2 as default terminal
  template:
    src: 0-iterm.zsh.j2
    dest: "{{ iterm_env_path }}"
  vars:
    iterm_version: "{{ lookup('file', iterm_version_path ) }}"
- name: Install Powerline font
  copy:
    src: "SourceCodePro+Powerline+Awesome+Regular.ttf"
    dest: "~/Library/Fonts"
- name: Install iTerm2 Profile
  copy:
    src: "com.googlecode.iterm2.plist"
    dest: "~/Library/Preferences/"
- name: Install powerlevel10k oh-my-zsh theme
  git:
    repo: "{{ powerlevel10k_repo }}"
    dest: "{{ powerlevel10k_path }}"
    depth: 1
- name: Populate powerlevel10k environment file
  lineinfile:
    dest: "{{ zshrc_path }}"
    state: present
    regexp: "^(export )?{{ item.key }}="
    line: "export {{ item.key }}={{ item.value }}"
  with_items: "{{ powerlevel10k_env_vars }}"
- name: Add powerlevel10k instant prompt config to .zshrc
  blockinfile:
    insertbefore: BOF
    path: "{{ zshrc_path }}"
    block: |
      # Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
      # Initialization code that may require console input (password prompts, [y/n]
      # confirmations, etc.) must go above this block, everything else may go below.
      if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
        source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
      fi
- name: Install powerlevel10k config
    copy:
      src: "p10k.zsh"
      dest: "~/.p10k.zsh"
- name: Install powerlevel10k config to .zshrc
  blockinfile:
    insertafter: EOF
    path: "{{ zshrc_path }}"
    block: |
      # To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
      [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh





